filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.log
    #- /opt/IBM/HTTPServer/logs/*.log
    #- /opt/IBM/WebSphere/AppServer/profiles/HOSTREPLACE/logs/HOSTREPLACE/System*.log
    #- /log/OFFLOG/*/*.log
    #- /log/OFFLOG/EMTA/*.log
    #- c:\programdata\elasticsearch\logs\*
  fields:
     host_ip: 192.168.100.100
# exclude_files: ['/log/OFFLOG/BACKUP/*', '/log/OFFLOG/TEMP/*', '.*-console.log', '.*-error.log']

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:
output.kafka:
  hosts: ["172.16.26.79:9092", "172.16.26.80:9092"]
  topic: "EMTA_FB_INPUT"
  codec.json:
    pretty: false

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

