filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.log
    #- /opt/IBM/HTTPServer/logs/*.log
    #- /opt/IBM/WebSphere/AppServer/profiles/HOSTREPLACE/logs/HOSTREPLACE/System*.log
    #- c:\programdata\elasticsearch\logs\*

# exclude_files: ['.*-console.log', '.*-error.log']

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:
output.kafka:
  hosts: ["10.10.10.10:9092", "10.10.10.11:9092"]
  topic: "FB_INPUT"
  codec.json:
    pretty: false

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

